### ISSUE TITLE
Cannot select between two credit cards with same name when paying 

### ISSUE THREAD

**Issue by danbaterisna** [AY2122S2-CS2113T-T10-4/tp#205]
**Reproduction:** Run the following two commands:
- `add /cc /n DBS /cb 1.0 /cl 10000`
- `add /cc /n DBS /cb 5.0 /cl 200000`

The output of `list /cc` should begin as follows:
![image](https://user-images.githubusercontent.com/8340533/162657091-db8c2521-c733-4d3a-bd5a-2b4a3b4cbf2d.png)

Now, try to pay for something using the second added card:
- `add /e /pm DBS /c Personal /d test /a 10.00 /t 01/01/2022`

**Expected outcome:** The second card is used to pay, and its balance is updated.

**Actual outcome:** The first card is used to pay, since the new balance shown is 9990, and not 199990:
![image](https://user-images.githubusercontent.com/8340533/162657304-87ef2cf4-9082-47a3-b683-e6e897fae294.png)

**Comment by SeanHoWB** [comment]
![image](https://user-images.githubusercontent.com/69450377/162660007-58b748ea-a824-4f76-b8d6-72511cd263b5.png)
fixed as shown, cannot add 2 credit card with same name. Should be in the codebase alr
