### ISSUE TITLE
DG Review

### ISSUE THREAD

**Issue by richwill28** [AY2122S2-CS2113T-T10-4/tp#92]
1. [Nitpick] Please update it to reflect your product name.
![image](https://user-images.githubusercontent.com/69445142/161007252-6c00916d-b719-433a-a108-30c905714218.png)

2. Overall organization of the DG is neat. Good job!

3. Most of the hyperlinks on the Content Page are not working.
![image](https://user-images.githubusercontent.com/69445142/161008571-79e78a77-6ade-465e-b106-e0fcc8bfee8b.png)

4. Not sure what is the purpose of this. Consider updating the DG, or removing this part if it's no longer needed.
![image](https://user-images.githubusercontent.com/69445142/161008960-de7fc8d5-1aee-4dea-b074-8196ac49d74e.png)

5. [Nitpick] The boxes (highlighted with red circles) are unnecessary. Consider removing them.
![image](https://user-images.githubusercontent.com/69445142/161009272-e1c0acbf-0f16-4ca4-b954-742d51ec7424.png)

6. Please update this part (or remove it).
![image](https://user-images.githubusercontent.com/69445142/161009555-576e9e4f-e5e1-43ed-9532-570c671b9cbb.png)

7. User stories does not seem to be complete. Please update it.
![image](https://user-images.githubusercontent.com/69445142/161009870-e47188f2-d013-4eba-8674-35ef212ce216.png)

8. Architecture diagram could benefit more with the usage of labels.
![image](https://user-images.githubusercontent.com/69445142/161010234-79c04a47-ea57-4b28-a160-1c85a734a49f.png)

9. Nice that different color schemes were used for different classes (in class and architecture diagrams). Consider using them for sequence diagrams as well.

**Comment by limjierui** [comment]
All issues have been cleared in multiple PRs by different people. Thanks TA for pointing these issues out.
